name: Workflow to say hello

on:
  push:

jobs:
  hello-job:
    runs-on: ubuntu-latest
    steps:
      - name: Say Hello
        run: echo "Hello, GitHub Actions!"

      - name: Show Node.js version
        run: node -v